# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.
# Project
version=1.1
group=com.mars.wishfulrecipes
java_version=21
deimos_version=2.7
# Common
mod_name=Wishful Recipes
mod_author=Mars
mod_id=wishfulrecipes
license=MIT
homepage=https://modrinth.com/mod/wishful-recipes
description=Dynamically generates recipes that should have already been in game
minecraft_version=1.21.3
minecraft_version_range=[1.21.2, 1.22)
neo_form_version=1.21.3-20241023.131943
parchment_minecraft=1.21
parchment_version=2024.11.10
# Fabric
fabric_version=0.109.0+1.21.3
fabric_loader_version=0.16.9
modmenu_version=12.0.0
# Forge
forge_version=53.0.21
forge_loader_version_range=[53,)
# NeoForge
neoforge_version=21.3.36-beta
neoforge_loader_version_range=[4,)
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
