plugins {
    id 'multiloader-loader'
    id 'net.minecraftforge.accesstransformers' version '5.0.3'
    id 'net.minecraftforge.gradle' version '[7.0.17,8)'
    id 'net.minecraftforge.jarjar' version '0.2.3'
}

minecraft {
    mappings channel: 'official', version: minecraft_version

    accessTransformer = true

    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformer = at
    }

    runs {
        configureEach {
            workingDir = layout.projectDirectory.dir('run')

            args "--mixin.config=${mod_id}.mixins.json"

            systemProperty 'eventbus.api.strictRuntimeChecks', 'true'
            systemProperty 'forge.enabledGameTestNamespaces', mod_id
        }

        register('client')

        register('server') {
            args '--nogui'
        }

        register('gameTestServer')

        register('data') {
            workingDir = layout.projectDirectory.dir('run-data')

            args '--mod', 'examplemod', '--all', '--output', layout.projectDirectory.dir('src/generated/resources'), '--existing', layout.projectDirectory.dir('src/main/resources')
        }
    }
}

sourceSets.main.resources.srcDir 'src/generated/resources'

repositories {
    minecraft.mavenizer(it) // In Kotlin, it = this
    maven {  url = "https://repo.spongepowered.org/maven" }
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
    mavenCentral()
}

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${minecraft_version}-${forge_version}")
    annotationProcessor 'net.minecraftforge:eventbus-validator:7.0-beta.10'
    // Forge's hack fix
    implementation('net.sf.jopt-simple:jopt-simple:5.0.4') { version { strictly '5.0.4' } }

    implementation "maven.modrinth:deimos:${project.minecraft_version}-forge-${project.deimos_version}"
}

jarJar.register() {
    archiveClassifier = ""
}

jar {
    manifest {
        attributes([
                "MixinConfigs": "${mod_id}.mixins.json"
        ])
    }
}

sourceSets.each {
    def dir = layout.buildDirectory.dir("sourcesSets/$it.name")
    it.output.resourcesDir = dir
    it.java.destinationDirectory = dir
}